version: '3'
services:
  dbpostgres:
    image: "postgres:11"
    container_name: "postgres_db"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jehailey
    ports:
      - "22222:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
    driver: local

networks:
  stock-alarmi-network:
    driver: bridge
